퀴즈 제한 시간 : 60 # 한 퀴즈 당 제한시간을 설정합니다. (단위 : 초)
힌트 공개 시간 : 10 # 몇 초마다 힌트를 공개할 것인지 설정합니다. (단위 : 초)
이미지 출력 : true # 곡 정보 공개 시 이미지를 출력할 것인지 설정합니다.
시간 기반 득점 사용 : true # 빨리 맞출 수록 점수룰 많이 주는 시간 기반 득정을 사용할 것인지 정합니다.
시간 기반 득점 최고 점수 : 5 # 시간 기반 득점의 최고 점수를 정합니다.
다음 퀴즈 출제 시간 : 20 # 자동 출제 시, 다음 출제까지의 대기시간을 정합니다.
사운드 볼륨 : 0.5 # 사운드 출력 볼륨을 정합니다.
힌트 기능 사용 : true # 힌트 기능을 사용할 것인지 정합니다.
유저 사운드 리스트 확인 가능 여부 : true # 유저가 사운드 리스트를 확인할 수 있게 할 것이지 정합니다.
정답 시 폭죽 사용 : true # 정답 시 정답자에게 폭죽을 생성할 것인지 정합니다.
게임 결과 발표 시 폭죽 사용 : true # 결과 발표 시 상위 등수 플레이어에게 폭죽을 생성할 것인지 정합니다.
사운드 리스트 정답 확인 가능 여부 (유저) : false # 유저가 사운드 리스트를 볼때, 사운드의 정답을 함께 보여줄 것인지 정합니다.
사운드 리스트 정답 확인 가능 여부 (관리자) : true # 관리자가 사운드 리스트를 볼때, 사운드의 정답을 함께 보여줄 것인지 정합니다.